version: '2'
services:
  
  falko-front:
    container_name: falko-front
    # image: alaxalves/front:1.4
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/bash -lc "npm install && npm run dev"
    volumes:
      - .:/Falko-2017.2-FrontEnd
    external_links:
      - falko20172backend_default
    ports:
      - 8080:8080
    networks:
      - default
      - falko20172backend_default

networks:
  falko20172backend_default: 
    external: true
     
    
