version: '2'
services:
  
  falko-front:
    container_name: falko-front
    image: alaxalves/front:1.5
    command: /bin/bash -lc "npm install && npm run dev"
    external_links:
      - falko20172backend_default
    ports:
      - 8080:8080
    networks:
      - default
    ipc: host    
